### ISSUE TITLE
More DWIM: Should be able to find valid /path/to/file:line strings inside sentences

### ISSUE THREAD

**Issue by xtaran** [kilobyte/e#4]
Currently, `e` is not able to handle full lines like this one properly, neither on STDIN, nor when the full line is passed as parameter:

```
Offending RSA key in /home/abe/.ssh/known_hosts:441
```

Interestingly it shows different behaviour with that line as commandline parameter and on STDIN:

1. On the commandline (unquoted) I got five files opened: `Offending`, `RSA`, `key`, `in` and the expected `/home/abe/.ssh/known_hosts` at line 441.
2. Piped via STDIIN I got `Offending RSA key in /home/abe/.ssh/known_hosts` (which doesn't exist) at line 441.

In both cases I'd have expected that `e` ignores everything than `/home/abe/.ssh/known_hosts:441`. Then again, I assume that if I'd have quoted the whole sentence in the first case, I would have gotten the same result as in the second case.

And yes, I'm aware that this would break the current handling of paths with spaces. But then again: When in the Unix world do you have code which emits warnings with path names with spaces in it? Having some words in front of the path seems way more common.

No pull request yet, as I'm not (yet) sure what's the best way to solve this.

**Comment by kilobyte** [comment]
My assumptions got broken anyway by a recent change to `git grep` — its output has now dropped the space after colon that all other programs I looked at have.  So I wonder how to parse things.

**Comment by kilobyte** [comment]
Actually, even regular `grep -nC` produces no space, and never did (only non-context `grep -n` does).  Thanks for poking me so I noticed this.  Thus, checking for :line at the end is broken.

I don't quite see how to fix that in a sane way while still allowing embedded colons.  So colons are quite on the same boat as spaces...
